[tool.poetry]
name = "autodonate-placeholder-plugin"
version = "0.1.1"
description = ""
authors = ["firesquare <team@firesquare.ru>"]
readme = "README.md"
repository = "https://github.com/fire-squad/autodonate-placeholder-plugin"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.2"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
